/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ProduitsIndexRouteImport } from './routes/produits.index'
import { Route as ProduitsArticleProductIdRouteImport } from './routes/produits.article.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsIndexRoute = ProduitsIndexRouteImport.update({
  id: '/produits/',
  path: '/produits/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsArticleProductIdRoute =
  ProduitsArticleProductIdRouteImport.update({
    id: '/produits/article/$productId',
    path: '/produits/article/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/produits/': typeof ProduitsIndexRoute
  '/produits/article/$productId': typeof ProduitsArticleProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/produits': typeof ProduitsIndexRoute
  '/produits/article/$productId': typeof ProduitsArticleProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/produits/': typeof ProduitsIndexRoute
  '/produits/article/$productId': typeof ProduitsArticleProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/contact'
    | '/produits/'
    | '/produits/article/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/contact'
    | '/produits'
    | '/produits/article/$productId'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/admin'
    | '/contact'
    | '/produits/'
    | '/produits/article/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  ProduitsIndexRoute: typeof ProduitsIndexRoute
  ProduitsArticleProductIdRoute: typeof ProduitsArticleProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits/': {
      id: '/produits/'
      path: '/produits'
      fullPath: '/produits/'
      preLoaderRoute: typeof ProduitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits/article/$productId': {
      id: '/produits/article/$productId'
      path: '/produits/article/$productId'
      fullPath: '/produits/article/$productId'
      preLoaderRoute: typeof ProduitsArticleProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  ProduitsIndexRoute: ProduitsIndexRoute,
  ProduitsArticleProductIdRoute: ProduitsArticleProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
