/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FavorisRouteImport } from './routes/favoris'
import { Route as LivraisonRouteImport } from './routes/livraison'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminImportRouteImport } from './routes/admin_.import'
import { Route as ProduitsIndexRouteImport } from './routes/produits.index'
import { Route as ProduitsSplatRouteImport } from './routes/produits.$'
import { Route as ApiAdminCheckImageRouteImport } from './routes/api/admin/check-image'
import { Route as ProduitsArticleProductIdRouteImport } from './routes/produits.article.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorisRoute = FavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => rootRouteImport,
} as any)
const LivraisonRoute = LivraisonRouteImport.update({
  id: '/livraison',
  path: '/livraison',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/admin_/import',
  path: '/admin/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsIndexRoute = ProduitsIndexRouteImport.update({
  id: '/produits/',
  path: '/produits/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsSplatRoute = ProduitsSplatRouteImport.update({
  id: '/produits/$',
  path: '/produits/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCheckImageRoute = ApiAdminCheckImageRouteImport.update({
  id: '/api/admin/check-image',
  path: '/api/admin/check-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitsArticleProductIdRoute =
  ProduitsArticleProductIdRouteImport.update({
    id: '/produits/article/$productId',
    path: '/produits/article/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/favoris': typeof FavorisRoute
  '/livraison': typeof LivraisonRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/panier': typeof PanierRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/import': typeof AdminImportRoute
  '/produits/$': typeof ProduitsSplatRoute
  '/produits/': typeof ProduitsIndexRoute
  '/api/admin/check-image': typeof ApiAdminCheckImageRoute
  '/produits/article/$productId': typeof ProduitsArticleProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/favoris': typeof FavorisRoute
  '/livraison': typeof LivraisonRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/panier': typeof PanierRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/import': typeof AdminImportRoute
  '/produits/$': typeof ProduitsSplatRoute
  '/produits': typeof ProduitsIndexRoute
  '/api/admin/check-image': typeof ApiAdminCheckImageRoute
  '/produits/article/$productId': typeof ProduitsArticleProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/favoris': typeof FavorisRoute
  '/livraison': typeof LivraisonRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/panier': typeof PanierRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin_/import': typeof AdminImportRoute
  '/produits/$': typeof ProduitsSplatRoute
  '/produits/': typeof ProduitsIndexRoute
  '/api/admin/check-image': typeof ApiAdminCheckImageRoute
  '/produits/article/$productId': typeof ProduitsArticleProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/contact'
    | '/favoris'
    | '/livraison'
    | '/mentions-legales'
    | '/panier'
    | '/sitemap.xml'
    | '/admin/import'
    | '/produits/$'
    | '/produits/'
    | '/api/admin/check-image'
    | '/produits/article/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/admin'
    | '/contact'
    | '/favoris'
    | '/livraison'
    | '/mentions-legales'
    | '/panier'
    | '/sitemap.xml'
    | '/admin/import'
    | '/produits/$'
    | '/produits'
    | '/api/admin/check-image'
    | '/produits/article/$productId'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/admin'
    | '/contact'
    | '/favoris'
    | '/livraison'
    | '/mentions-legales'
    | '/panier'
    | '/sitemap.xml'
    | '/admin_/import'
    | '/produits/$'
    | '/produits/'
    | '/api/admin/check-image'
    | '/produits/article/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  FavorisRoute: typeof FavorisRoute
  LivraisonRoute: typeof LivraisonRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PanierRoute: typeof PanierRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminImportRoute: typeof AdminImportRoute
  ProduitsSplatRoute: typeof ProduitsSplatRoute
  ProduitsIndexRoute: typeof ProduitsIndexRoute
  ApiAdminCheckImageRoute: typeof ApiAdminCheckImageRoute
  ProduitsArticleProductIdRoute: typeof ProduitsArticleProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoris': {
      id: '/favoris'
      path: '/favoris'
      fullPath: '/favoris'
      preLoaderRoute: typeof FavorisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/livraison': {
      id: '/livraison'
      path: '/livraison'
      fullPath: '/livraison'
      preLoaderRoute: typeof LivraisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/import': {
      id: '/admin_/import'
      path: '/admin/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits/': {
      id: '/produits/'
      path: '/produits'
      fullPath: '/produits/'
      preLoaderRoute: typeof ProduitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits/$': {
      id: '/produits/$'
      path: '/produits/$'
      fullPath: '/produits/$'
      preLoaderRoute: typeof ProduitsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/check-image': {
      id: '/api/admin/check-image'
      path: '/api/admin/check-image'
      fullPath: '/api/admin/check-image'
      preLoaderRoute: typeof ApiAdminCheckImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produits/article/$productId': {
      id: '/produits/article/$productId'
      path: '/produits/article/$productId'
      fullPath: '/produits/article/$productId'
      preLoaderRoute: typeof ProduitsArticleProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  FavorisRoute: FavorisRoute,
  LivraisonRoute: LivraisonRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PanierRoute: PanierRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminImportRoute: AdminImportRoute,
  ProduitsSplatRoute: ProduitsSplatRoute,
  ProduitsIndexRoute: ProduitsIndexRoute,
  ApiAdminCheckImageRoute: ApiAdminCheckImageRoute,
  ProduitsArticleProductIdRoute: ProduitsArticleProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
